back:
  enabled: false
#  etcBhsSecretName: etc-bhs

front:
  enabled: false
#  etcBhsSecretName: etc-bhs

redis:
  enabled: false

global:
  enableSitemap: false
  debug: false
  environmentName: staging
  opsRepoSlug: Beit-Hatfutsot/mojp-k8s
  opsRepoBranch: master

minio:
  enabled: false
#  envVarsSecretName: env-vars
#  persistentDiskName: dbs-production-minio-data

nginx:
  htpasswdSecretName: nginx-htpasswd

pipelines:
  enabled: false
#  envVarsSecretName: env-vars
#  image: orihoch/mojp-dbs-back-pipelines:sitemap-aws-principal-patch
#  sitemapEsHost: bhs-prod-db
#  sitemapEsIndex: mojp-prod

traefik:
  acmeDomains: |
    [[acme.domains]]
      main = "staging-dbs-bh.uumpa.net"
    [[acme.domains]]
      main = "api.staging-dbs-bh.uumpa.net"
  acmeEmail: ori@uumpa.com
#  enableCjhProxy: true
#  frontHostRule: "Host: staging-dbs.bh.org.il;"
  loadBalancerIP: 35.188.195.70
  nodeHostName: gke-mojp2-default-pool-2a2857ee-0sn6
  rootHost: "staging-dbs-bh.uumpa.net"
#  backupJob: true

kibana:
  enabled: true
  elasticsearchUrl: http://mojp-dbs-elasticsearch:9200

elasticsearch:
  enabled: false

mojp-dbs-pipelines:
  enabled: false
#  clearmashGetEntityIdsJob: true
#  clearmashSplitEntitiesFoldersJob: true
#  clearmashDownloadEntitiesJob: true
#  clearmashPrepForElasticsearch: true

mojp-dbs-searchapi:
  enabled: true
  ES_HOST: mojp-dbs-elasticsearch

mojp-dbs-searchapp:
  enabled: true

mojp-dbs-elasticsearch:
  enabled: true
