back:
  etcBhsSecretName: etc-bhs

front:
  etcBhsSecretName: etc-bhs

global:
  defaultNodePool: staging-pool
  enableSitemap: false
  debug: true

minio:
  enabled: false

nginx:
  htpasswdSecretName: nginx-htpasswd

pipelines:
  enabled: false

traefik:
  acmeDomains: |
    [[acme.domains]]
      main = "staging-dbs.bh.org.il"
    [[acme.domains]]
      main = "api.staging-dbs.bh.org.il"
  acmeEmail: ori@uumpa.com
  enableCjhProxy: true
  frontHostRule: "Host: staging-dbs.bh.org.il;"
  loadBalancerIP: 35.205.137.62
  nodeHostName: gke-mojp-staging-pool-00ace2a7-2kz7
  rootHost: "staging-dbs.bh.org.il"

kibana:
  enabled: false
  elasticsearchUrl: http://elasticsearch:9200
  nodePool: staging-debug-pool

elasticsearch:
  enabled: false
  nodePool: staging-debug-pool

mojp-dbs-pipelines:
  enabled: true
  clearmashGetEntityIdsJob:
    name: clearmash-get-entity-ids
    nodePool: default-pool
    image: gcr.io/bh-org-01/mojp-dbs-pipelines:132db443cac078af5c6112b8fdebff44f9f5bd3f
    pipelinesScript: dpp run ./clearmash/web-content-folder-item-ids
    secretEnvFrom: clearmash
    opsImage: orihoch/sk8sops@sha256:6a7bddfa3f523306f5b62391b95b1cd00407053aa5a53f98dc643b5e344228ed
    GS_BUCKET_NAME: mojp-dbs-pipelines-clearmash-scheduled-job
    GCLOUD_PROJECT: bh-org-01
    opsSecretName: ops
    # gsutilSyncArgs: "-a public-read"
    # schedule: "@weekly"
