back:
  etcBhsSecretName: etc-bhs

front:
  etcBhsSecretName: etc-bhs

global:
  defaultNodePool: staging-pool
  enableSitemap: false
  debug: true
  environmentName: staging
  opsRepoSlug: Beit-Hatfutsot/mojp-k8s
  opsRepoBranch: master

minio:
  enabled: false

nginx:
  htpasswdSecretName: nginx-htpasswd

pipelines:
  enabled: false

traefik:
  acmeDomains: |
    [[acme.domains]]
      main = "staging-dbs.bh.org.il"
    [[acme.domains]]
      main = "api.staging-dbs.bh.org.il"
  acmeEmail: ori@uumpa.com
  enableCjhProxy: true
  frontHostRule: "Host: staging-dbs.bh.org.il;"
  loadBalancerIP: 35.205.137.62
  nodeHostName: gke-mojp-staging-pool-00ace2a7-2kz7
  rootHost: "staging-dbs.bh.org.il"

kibana:
  enabled: false
  elasticsearchUrl: http://elasticsearch:9200
  nodePool: staging-debug-pool

elasticsearch:
  enabled: false
  nodePool: staging-debug-pool


mojp-dbs-pipelines:
  enabled: true
  clearmashGetEntityIdsJob:
    name: clearmash-get-entity-ids
    # schedule: "@daily"
    nodePool: default-pool
    image: gcr.io/bh-org-01/mojp-dbs-pipelines:35ec0999d4cbafe444d01f8c8b799706d7883ead
    pipelinesScript: dpp run ./clearmash/web-content-folder-item-ids
    secretEnvFrom: clearmash
    GS_BUCKET_NAME: mojp-dbs-pipelines-data
    OUTPUT_PATH_PREFIX: clearmash-get-entity-ids-job-
    # INITIAL_SYNC_SCRIPT: gsutil -m rsync -r gs://sk8s-pipelines-data/noise-2017-12-06/ /pipelines/data/
    opsSecretName: ops


    # gsutilSyncArgs: "-a public-read"
    # schedule: "@weekly"
#  clearmashDownloadEntitiesJob:
#    name: clearmash-download-entities
#    nodePool: default-pool
#    image: gcr.io/bh-org-01/mojp-dbs-pipelines:96ce218ec8edbf85801581de1a1596595d4bd057
#    syncScript: gsutil -m rsync -r gs://mojp-dbs-pipelines-clearmash-scheduled-job/2017-12-26-18-11/ /pipelines/data/
#    pipelinesScript: dpp run ./clearmash/download-entities
#    secretEnvFrom: clearmash
#    opsImage: orihoch/sk8sops@sha256:6a7bddfa3f523306f5b62391b95b1cd00407053aa5a53f98dc643b5e344228ed
#    GS_BUCKET_NAME: mojp-dbs-pipelines-clearmash-scheduled-job
#    GCLOUD_PROJECT: bh-org-01
#    opsSecretName: ops
#    # gsutilSyncArgs: "-a public-read"
#    # schedule: "@weekly"
