back:
    image: gcr.io/bh-org-01/mojp-dbs-back:f4c5a0c0b7c0d77faa8c07466f3fd57f8b7f0786
    etcBhsSecretName: etc-bhs

front:
    image: gcr.io/bh-org-01/mojp-dbs-front:5b1030d34e77e60db1b8384a3b68f690de5a4a9c
    etcBhsSecretName: etc-bhs

minio:
    envVarsSecretName: env-vars
    persistentDiskName: dbs-production-minio-data

pipelines:
    image: gcr.io/bh-org-01/orihoch-dbs-back-pipelines:f36618e2fdb61813ef0fb473bd85d1f11437ee3b
    envVarsSecretName: env-vars
    sitemapEsHost: bhs-prod-db
    sitemapEsIndex: mojp-prod

traefik:
  # traefik uses a shared host path to enable automatic let's encrypt renewal
  # this can be modified to a more complex architecture with consul but not worth it IMO
  # deploying on new nodes you should remove this value to allow traefik to be scheduled on any node then add the hostname
  nodeHostName: gke-mojp-default-pool-33bac5d8-rm42

global:
    defaultNodePool: default-pool
