{{ if .Values.enabled }}{{ if .Values.clearmashGetEntityIdsJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: clearmash-get-entity-ids
spec:
  template:
    metadata:
      name: clearmash-get-entity-ids
    spec:
      containers:
      - name: pipelines
        image: {{ .Values.clearmashGetEntityIdsJob.image }}
        # updated Jan 12, 2018
        resources: {"requests": {"cpu": "100m", "memory": "800Mi"}}
        command:
        - bash
        - "-c"
        - |
          rm -f /pipelines/data/done &&\
          dpp run ./clearmash/web-content-folder-item-ids &&\
          touch /pipelines/data/done
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        envFrom:
        - secretRef:
            name: clearmash
      - name: ops
        image: gcr.io/uumpa-public/sk8s-google-storage-sync:v0.0.2
        resources: {"requests": {"cpu": "1m", "memory": "2Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-dbs-pipelines-data
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      - name: k8s-ops
        secret:
          secretName: ops
      - name: data
        emptyDir: {}
      restartPolicy: Never
{{ end }}{{ end }}
