{{ if .Values.enabled }}{{ if .Values.clearmashDumpToElasticsearchJob }}
apiVersion: batch/v1
kind: Job
#apiVersion: batch/v1beta1
#kind: CronJob
metadata:
  name: clearmash-dump-to-elasticsearch
spec:
#  schedule: "@daily"
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
  template:
    metadata:
      name: clearmash-dump-to-elasticsearch
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.clearmashDumpToElasticsearchJob.nodePool | quote }}
      containers:
      - name: pipelines
        image: gcr.io/bh-org-01/mojp-dbs-pipelines:53ce94bf7275e26a259c80da84e335995546d41f
        command:
        - bash
        - "-c"
        - |
          while ! [ -e /pipelines/data/synced ]; do sleep 5 && echo .; done && rm -f /pipelines/data/synced &&\
          dpp run ./clearmash/dump_entities_to_elasticsearch &&\
          rm -rf data/clearmash/places &&\
          rm -rf data/clearmash/familynames &&\
          rm -rf data/clearmash/movies &&\
          rm -rf data/clearmash/personalities &&\
          rm -rf data/clearmash/photounits &&\
          touch /pipelines/data/done
        volumeMounts: [{"name": "data", "mountPath": "/pipelines/data"}]
        env:
        - name: DPP_ELASTICSEARCH
          value: elasticsearch:9200
      - name: ops
        image: orihoch/sk8sops:pipelines-gcs@sha256:a6e8f94c2e68fc8da552abcbdac865763d40e79895b87ff06a98ebd588070cf0
        resources: {"requests": {"cpu": "0.01", "memory": "100Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-dbs-pipelines-data
        - name: INITIAL_SYNC_SCRIPT
          value: >
                 mkdir -p /pipelines/data/clearmash/places &&
                 mkdir -p /pipelines/data/clearmash/familynames &&
                 mkdir -p /pipelines/data/clearmash/movies &&
                 mkdir -p /pipelines/data/clearmash/personalities &&
                 mkdir -p /pipelines/data/clearmash/photounits &&
                 gsutil -m rsync -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/places/ /pipelines/data/clearmash/places/ &&
                 gsutil -m rsync -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/familynames/ /pipelines/data/clearmash/familynames/ &&
                 gsutil -m rsync -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/movies/ /pipelines/data/clearmash/movies/ &&
                 gsutil -m rsync -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/personalities/ /pipelines/data/clearmash/personalities/ &&
                 gsutil -m rsync -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/photounits/ /pipelines/data/clearmash/photounits/
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      # this is the k8s ops secret, see https://github.com/OriHoch/sk8s-ops/blob/master/README.md#secrets
      - name: k8s-ops
        secret:
          secretName: ops
      # empty dir is stored on host and shared between all container in pod, we use it to sync data between the pods
      - name: data
        emptyDir: {}
      restartPolicy: Never
{{ end }}{{ end }}
