{{ if .Values.enabled }}{{ if .Values.clearmashSplitEntitiesFoldersJob }}
apiVersion: batch/v1
kind: Job
#apiVersion: batch/v1beta1
#kind: CronJob
metadata:
  name: clearmash-split-entities-folders
spec:
#  schedule: "@daily"
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
  template:
    metadata:
      name: clearmash-split-entities-folders
    spec:
      containers:
      - name: pipelines
        image: gcr.io/bh-org-01/mojp-dbs-pipelines:94f69b507a682400c1000509d6838d22973e5231
        command:
        - bash
        - "-c"
        - |
          while ! [ -e /pipelines/data/synced ]; do sleep 5 && echo .; done && rm -f /pipelines/data/synced &&\
          dpp run ./clearmash/folders &&\
          dpp run ./clearmash/entity-ids &&\
          rm -rf data/clearmash/web-content-folder-entity-ids &&\
          touch /pipelines/data/done
        volumeMounts: [{"name": "data", "mountPath": "/pipelines/data"}]
      - name: ops
        image: orihoch/sk8sops:pipelines-gcs@sha256:a6e8f94c2e68fc8da552abcbdac865763d40e79895b87ff06a98ebd588070cf0
        resources: {"requests": {"cpu": "0.01", "memory": "100Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-dbs-pipelines-data
        - name: DISABLE_TIMESTAMP
          value: "1"
        - name: INITIAL_SYNC_SCRIPT
          value: gsutil -m rsync -r gs://mojp-dbs-pipelines-data/clearmash-get-entity-ids-job-2017-12-29-05-00 /pipelines/data/
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      # this is the k8s ops secret, see https://github.com/OriHoch/sk8s-ops/blob/master/README.md#secrets
      - name: k8s-ops
        secret:
          secretName: ops
      # empty dir is stored on host and shared between all container in pod, we use it to sync data between the pods
      - name: data
        emptyDir: {}
      restartPolicy: Never
{{ end }}{{ end }}
