{{ if .Values.enabled }}{{ if .Values.clearmashSplitEntitiesFoldersJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: clearmash-split-entities-folders
spec:
  template:
    metadata:
      name: clearmash-split-entities-folders
    spec:
      containers:
      - name: pipelines
        image: {{ .Values.clearmashSplitEntitiesFoldersJob.image }}
        command:
        - bash
        - "-c"
        - |
          while ! [ -e /pipelines/data/synced ]; do sleep 5 && echo .; done && rm -f /pipelines/data/synced &&\
          dpp run ./clearmash/folders &&\
          dpp run ./clearmash/entity-ids &&\
          rm -rf data/clearmash/web-content-folder-entity-ids &&\
          touch /pipelines/data/done
        volumeMounts: [{"name": "data", "mountPath": "/pipelines/data"}]
      - name: ops
        image: orihoch/sk8sops:pipelines-gcs@sha256:c232fcbd4ffff456b9cb9312a4b7d62cec8c0fe6b36bf31e50625a618f129746
        resources: {"requests": {"cpu": "1m", "memory": "2Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-dbs-pipelines-data
        - name: INITIAL_SYNC_SCRIPT
          value: gsutil -m rsync -r {{ .Values.clearmashSplitEntitiesFoldersJob.input }} /pipelines/data/
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      # this is the k8s ops secret, see https://github.com/OriHoch/sk8s-ops/blob/master/README.md#secrets
      - name: k8s-ops
        secret:
          secretName: ops
      # empty dir is stored on host and shared between all container in pod, we use it to sync data between the pods
      - name: data
        emptyDir: {}
      restartPolicy: Never
{{ end }}{{ end }}
