apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redirector-app
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redirector-app
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: app
        image: docker.pkg.github.com/beit-hatfutsot/dbs-front/redirector-app:latest
        ports:
        - {containerPort: 5000}
