apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redirector-app
  namespace: production
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redirector-app
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: app
        image: docker.pkg.github.com/beit-hatfutsot/dbs-front/redirector-app:v7
        resources: {"requests": {"cpu": "50m", "memory": "200Mi"}, "limits": {"cpu": "150m", "memory": "600Mi"}}
        ports:
        - {containerPort: 5000}
        env:
          - name: REDIRECTOR_ENABLED
            value: "yes"
