{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mojp-dbs-elasticsearch
spec:
  selector:
    app: mojp-dbs-elasticsearch
  ports:
  - port: 9200
    name: "9200"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mojp-dbs-elasticsearch
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: mojp-dbs-elasticsearch
    spec:
      containers:
      - name: sysctl-conf
        image: busybox:1.26.2
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262166 && while true; do sleep 86400; done"]
        resources:
          requests:
            cpu: 1m
            memory: 5Mi
        securityContext:
          privileged: true
      - image: budgetkey/open-budget-elasticsearch
        name: elasticsearch
        resources:
          requests:
            cpu: 200m
            memory: 2Gi
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        ports:
        - containerPort: 9200
      - name: ops
        image: orihoch/sk8sops:pipelines-gcs@sha256:a6e8f94c2e68fc8da552abcbdac865763d40e79895b87ff06a98ebd588070cf0
        resources: {"requests": {"cpu": "0.01", "memory": "100Mi"}}
        command:
        - bash
        - "-c"
        - |
          source ~/.bashrc;
          gcloud config set project "bh-org-01" &&\
          mkdir -p /pipelines/data/clearmash/places && mkdir -p /pipelines/data/clearmash/familynames && mkdir -p /pipelines/data/clearmash/movies &&\
          mkdir -p /pipelines/data/clearmash/personalities && mkdir -p /pipelines/data/clearmash/photounits &&\
          gsutil -m rsync -x '^done|synced$' -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/places/ /pipelines/data/clearmash/places/ &&\
          gsutil -m rsync -x '^done|synced$' -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/familynames/ /pipelines/data/clearmash/familynames/ &&\
          gsutil -m rsync -x '^done|synced$' -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/movies/ /pipelines/data/clearmash/movies/ &&\
          gsutil -m rsync -x '^done|synced$' -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/personalities/ /pipelines/data/clearmash/personalities/ &&\
          gsutil -m rsync -x '^done|synced$' -r gs://mojp-dbs-pipelines-data/2018-01-03-07-58/clearmash/photounits/ /pipelines/data/clearmash/photounits/ &&\
          ls -lah /pipelines/data/clearmash/{places,familynames,movies,personalities,photounits} &&\
          touch /pipelines/data/synced &&\
          echo "sync complete, going to sleep" &&\
          while true; do sleep 86400; done
        volumeMounts:
        - name: data
          mountPath: /pipelines/data
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      - name: pipelines
        image: gcr.io/bh-org-01/mojp-dbs-pipelines:53ce94bf7275e26a259c80da84e335995546d41f
        command:
        - bash
        - "-c"
        - |
          while ! [ -e /pipelines/data/synced ]; do sleep 5 && echo .; done && rm -f /pipelines/data/synced &&\
          dpp run ./clearmash/dump_entities_to_elasticsearch &&\
          rm -rf data/clearmash/places && rm -rf data/clearmash/familynames && rm -rf data/clearmash/movies &&\
          rm -rf data/clearmash/personalities && rm -rf data/clearmash/photounits &&\
          touch /pipelines/data/done &&\
          echo "pipelines complete, going to sleep" &&\
          while true; do sleep 86400; done
        readinessProbe:
          exec:
            command:
            - cat
            - /pipelines/data/done
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts: [{"name": "data", "mountPath": "/pipelines/data"}]
        env:
        - name: DPP_ELASTICSEARCH
          value: localhost:9200
      volumes:
      - name: k8s-ops
        secret:
          secretName: ops
      - name: data
        emptyDir: {}
{{ end }}
