{{ if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: "9200"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: sysctl-conf
        image: busybox:1.26.2
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262166 && while true; do sleep 86400; done"]
        resources:
          limits:
            cpu: 1m
            memory: 5Mi
          requests:
            cpu: 1m
            memory: 5Mi
        securityContext:
          privileged: true
      - image: budgetkey/open-budget-elasticsearch
        name: elasticsearch
        ports:
        - containerPort: 9200
{{ end }}
