{{ if .Values.front.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: front}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: front}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - image: {{ .Values.front.image | quote }}
        name: front
        ports:
        - {containerPort: 80}
        resources:
          requests: {cpu: 20m}
        volumeMounts:
        - {mountPath: /etc/bhs, name: etc-bhs, readOnly: true}
      volumes:
      - name: etc-bhs
        secret: 
          secretName: {{ .Values.front.etcBhsSecretName | quote }}
---
apiVersion: v1
kind: Service
metadata: {name: front}
spec:
  ports:
  - port: 80
  selector: {app: front}
{{ end }}
