{{ if .Values.kibana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-conf
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: {{ .Values.kibana.elasticsearchUrl | quote }}
{{ end }}
