{{ if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.kibana.nodePool | quote }}
      containers:
      - image: kibana:5.3
        name: kibana
        ports:
        - containerPort: 5601
{{ end }}
