{{ if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: "80"
    port: 80
  {{ if .Values.pipelines.enabled }}
  - name: "8081"
    port: 8081
  {{ end }}
  {{ if .Values.global.enableSitemap }}
  - name: "8082"
    port: 8082
  {{ end }}
  {{ if .Values.kibana.enabled }}
  - name: "8083"
    port: 8083
  {{ end }}
  {{ if .Values.elasticsearch.enabled }}
  - name: "8084"
    port: 8084
  {{ end }}
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{.Values.nginx.replicas | default "1"}}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # update the pod on nginx-conf changes
        checksum/config: {{ include (print $.Template.BasePath "/nginx-conf.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        {{ if .Values.pipelines.enabled }}
        - containerPort: 8081
        {{ end }}
        {{ if .Values.global.enableSitemap }}
        - containerPort: 8082
        {{ end }}
        {{ if .Values.kibana.enabled }}
        - containerPort: 8083
        {{ end }}
        resources:
          requests:
            cpu: 1m
            memory: 10Mi
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        {{ if .Values.nginx.htpasswdSecretName }}
        - name: nginx-htpasswd
          mountPath: /etc/nginx/htpasswd
          readOnly: true
        {{ end }}
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      {{ if .Values.nginx.htpasswdSecretName }}
      - name: nginx-htpasswd
        secret:
          secretName: {{ .Values.nginx.htpasswdSecretName }}
      {{ end }}
{{ end }}
