{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gentrees-server
spec:
  selector:
    app: gentrees-server
  ports:
  - port: 3000
    name: "3000"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gentrees-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gentrees-server
    spec:
      containers:
      - name: server
        image: {{ .Values.serverImage | default "orihoch/beit-hatfutsot-gentrees-app-server:latest" | quote }}
        resources: {"requests": {"cpu": "20m", "memory": "50Mi"}, "limits": {"cpu": "100m", "memory": "400Mi"}}
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://gentrees-mongo:27017/gentreeDb
        - name: APP_CONFIG
          value: appConfig.cthulu.json
        - name: SMS_API_KEY
          valueFrom: {secretKeyRef: {name: gentrees, key: SMS_API_KEY}}
        - name: SMS_API_SECRET
          valueFrom: {secretKeyRef: {name: gentrees, key: SMS_API_SECRET}}
{{ end }}
