back:
  etcBhsSecretName: etc-bhs

front:
  etcBhsSecretName: etc-bhs

global:
  defaultNodePool: default-pool
  enableSitemap: true
  debug: false

minio:
  envVarsSecretName: env-vars
  persistentDiskName: dbs-production-minio-data

nginx:
  htpasswdSecretName: nginx-htpasswd

pipelines:
  envVarsSecretName: env-vars
  image: orihoch/mojp-dbs-back-pipelines:sitemap-aws-principal-patch
  sitemapEsHost: bhs-prod-db
  sitemapEsIndex: mojp-prod

traefik:
  acmeDomains: |
    [[acme.domains]]
      main = "test-dbs.bh.org.il"
    [[acme.domains]]
      main = "test-api.dbs.bh.org.il"
    [[acme.domains]]
      main = "api.dbs.bh.org.il"
    [[acme.domains]]
      main = "dbs.bh.org.il"
  acmeEmail: ori@uumpa.com
  enableCjhProxy: true
  frontHostRule: "Host: dbs.bh.org.il, test-dbs.bh.org.il;"
  loadBalancerIP: 35.205.123.187
  nodeHostName: gke-mojp-default-pool-33bac5d8-rm42
  rootHost: "dbs.bh.org.il"

kibana:
  enabled: true
  elasticsearchUrl: http://elasticsearch:9200
  nodePool: debug-pool

elasticsearch:
  enabled: true
  nodePool: debug-pool
