apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: mongo
        image: mongo:4.2
        ports:
        - {containerPort: 27017}
        resources: {{ .Values.resources }}
        volumeMounts:
        - name: mongo
          mountPath: /data/db
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-mongo
